[project]
name = "llm-chatbot-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "litellm>=1.75.4",
    "openai>=1.99.6",
    "pytest>=8.4.1",
]
